# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: payload.proto for package ''

require 'grpc'
require '/Users/mekari/learn/comparing-rest-grpc/lib/payload_pb.rb'

module Payload
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Payload'

    rpc :GetPayload, PayloadReq, PayloadResp
  end

  Stub = Service.rpc_stub_class
end
