# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("payload.proto", :syntax => :proto3) do
    add_message "PayloadReq" do
    end
    add_message "PayloadResp" do
      optional :data, :string, 1
    end
  end
end

PayloadReq = Google::Protobuf::DescriptorPool.generated_pool.lookup("PayloadReq").msgclass
PayloadResp = Google::Protobuf::DescriptorPool.generated_pool.lookup("PayloadResp").msgclass
