# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import payload_pb2 as payload__pb2


class PayloadStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPayload = channel.unary_unary(
        '/Payload/GetPayload',
        request_serializer=payload__pb2.PayloadReq.SerializeToString,
        response_deserializer=payload__pb2.PayloadResp.FromString,
        )


class PayloadServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPayload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PayloadServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPayload': grpc.unary_unary_rpc_method_handler(
          servicer.GetPayload,
          request_deserializer=payload__pb2.PayloadReq.FromString,
          response_serializer=payload__pb2.PayloadResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Payload', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
